# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftranslate.proto\x12\ttranslate\"D\n\x12TranslationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x66romLang\x18\x02 \x01(\t\x12\x0e\n\x06toLang\x18\x03 \x01(\t\"3\n\x13TranslationResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t2Z\n\nTranslator\x12L\n\tTranslate\x12\x1d.translate.TranslationRequest\x1a\x1e.translate.TranslationResponse\"\x00\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\001.'
  _globals['_TRANSLATIONREQUEST']._serialized_start=30
  _globals['_TRANSLATIONREQUEST']._serialized_end=98
  _globals['_TRANSLATIONRESPONSE']._serialized_start=100
  _globals['_TRANSLATIONRESPONSE']._serialized_end=151
  _globals['_TRANSLATOR']._serialized_start=153
  _globals['_TRANSLATOR']._serialized_end=243
# @@protoc_insertion_point(module_scope)
